### ISSUE TITLE
Chshel forgets aktual page and currsor position

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#167]
Now every time you chance view or switch the program, chshel forhet the actual page and line. I work intensive with other editors. So you permanently search the actual working position...

Before it remember the positions of all sites, this was usefull.

**Comment by radimitrov** [comment]
Nothing has changed. It still remembers the file and position. 
It is just a bit passive about saving it. I just updated it to save it more actively.
Though if it the first save since startup you still need to give it about a second when minimizing before you kill the app.

**Comment by Alisis33** [comment]
There is something wrong in the mechanics. I hafe to go back to my aktual page, and search the line, over and over again.

After some activitys it swich to a wrong page.

And it looses the memory for UnDo too.

I have several code pages in directories if this helps.

**Comment by Alisis33** [comment]
Ps
... in working time. Not only after a new start.

**Comment by Alisis33** [comment]
The pattern is like this
I work on multiple pages, but one mainly.

Start compiler
End the it
..It flips to a other page/file

Or
swich program without closing chshel.
Come back
..flip to wrong file

And because it switches files, the UnDo is gone.

The memory where you was in witch file was bugi after chshel was updated from *.cshpro to *. chproj. But now you save file more often and the bug show up not only by starting, but in worktime too.
I think the storage where you are aktualy not work right. Maybe it should be done allways when the file get saved.

**Comment by radimitrov** [comment]
The storage method is irrelevant. Just try the new update? It should always save before loading another project now.

**Comment by Alisis33** [comment]
Now in 2.5.123 the described bug seams gone, but I have to work with it a while.

but new bugs show up....
The implemented TTF in assets is correctly used in chshel, but not anymore in apk. The installed apk Programm not find the TTF.

There are double entrys in csproj, causing dictionary errors and the project gets broken and has to be reloaded.

I get randomly a error cs8021 now, and csshel not find the assemblys anymore.

The package name in settings still resets to default ....

Maybe this data base is broken.
If I can be honest, this is bad practic anyway to store Infos outside of the users access. All should be in csproj or a extra file.

All is very bugy in this version.
I am scared to update the software now...

**Comment by radimitrov** [comment]
As far I know the project class no longer creates double entries. You will have to provide steps to reproduce that. It doesn't aim to remove existing duplicate entries, but that doesn't disrupt the loading project. Are you getting key already exists error? Post the stack trace here.
The package name changes as it should (attached a vid). If you break the format too much it will be forced to reset like this: "com.companyname." + pkgNameStr.Split(".").Last().
And that database approach exists as to not deviate from the ".csproj" contents too much and to not pollute the filesystem with hundreds of extra files. Giving users access to it, well that is how it truly gets broken.

CS8021? That can only happen if the ".dll" it is trying to load is broken. There are only 2 possible causes.
1. After an update you terminated the app before it finished extracting the DLLs. Unlikely, as it should do it again on the next startup.
2. You don't have enough storage space to extract the DLLs. More likely, but the app should refuse to start completely until you free up enough space. 

https://user-images.githubusercontent.com/56889141/173288380-8c4779a9-03b1-436b-a02f-70af05e71b7a.mp4

**Comment by Alisis33** [comment]
For cs8021 and the "dublicate in dictionary" happent a few times after the update. Once I was in the main menu (up right).
I could not find the pattern jet. Most liekly it happens if joy fast to application switch, compile and other a actions.

**Comment by Alisis33** [comment]
About the company name,
I name it
com.cmname.lable
I only changet the middle part.

What happens with this Infos, if I change the name of the directory of the project?
Or I move/open it in a other IDE, or move it to other devices?

**Comment by Alisis33** [comment]
Why is the TTF now wrong in the compilat? Before the update it worked.
I dont know if this is all related, but all show up after the update.

**Comment by Alisis33** [comment]
You close it? The page memory is OK now, but the others not, even when off topic.
I can open a new one for 
* Lost asset TTF.
* And file rename.
* Project settings.

cs8021 show up 4 times, and now not anymore.

Yes I seen your video.
Your test pattern is wrong.
Change company name.
Open a other project.
Open the 1. Again


I try to find changes done in chproj

The TTF ar now listed
Assets/  before
Assets\  now
should be no problem, but...
Maybe /\ relatet? That would be very odd.

A before wrong empty cs entry is corrected now.

Rename a ggg.cs to ppp.cs and check the change in csproj. My version not change it.

And it is strange the cs8021 error not show up again, for now.
Maybe /\ relatet too? That would be very very odd.

In case, I have ! _ characters in the path.
